application: playnicewithothersnet
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
- url: /scripts
  static_dir: scripts
- url: /css
  static_dir: css
- url: /pages
  static_dir: pages 
- url: /
  static_files: pages/index.html
  upload: pages/index.html
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /c4.*
  script: c4.py
- url: /.*
  script: splash.py
